name: "scan2html"
repository: github.com/fatihtokus/scan2html-test
version: "0.0.2-alpha"
usage: scan targets into a smart html file
description: |-
  A Trivy plugin that scans and outputs the results to a html file.
  trivy scan2html [-h,--help] command target filename
platforms:
  - selector:
      os: windows
    uri: https://github.com/fatihtokus/scan2html-test/releases/download/v0.0.2-alpha/scan2html.tar.gz
    bin: ./scan2html.sh
  -
    uri: https://github.com/fatihtokus/scan2html-test/releases/download/v0.0.2-alpha/scan2html.tar.gz
    bin: ./scan2html
