name: Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      reportTemplate: 'report_template.html'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compress
        run: tar -zcvf README.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scan2html.tar.gz
